# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 99ede845a0b52b7ea8f14b82082071a78be81e1e19e589a55f75b26d461de4e6f3c2122dc328771d6b57f8387177d10162ddd0a3add70aa50b564bc2fb054a7c

test:
  secret_key_base: 03e9175901602a88e1a920b5137450d63790564eeec6c7bd653df529f9f3861eb87014acb1869bbfc000b91213694d1741a6fb3fbbeae66ef65cdfe196ca8704

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
